go.property("target", vmath.vector3())

function init(self)
	local pos = go.get_position()
	local time = vmath.length(self.target - pos)
	go.animate(".", "position", go.PLAYBACK_ONCE_FORWARD, self.target, go.EASING_LINEAR, time / 30, 0, function() go.delete() end)
	particlefx.play("#pfx")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		for _ = 1, 3 do
			factory.create("#fb-fac")
		end
		go.delete()
	end
end

